services:
  frontend:
    build:
      context: ./lt-rank
      args:
        - VITE_API_URL=/api
        - VITE_USE_MOCK=false
        - VITE_WEB_URL=https://ltrust.tw
    container_name: lt-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./ltutor
    container_name: lt-backend
    environment:
      - CI_ENVIRONMENT=production
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: lt-redis
    networks:
      - app-network
    volumes:
      - redis_data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
